name: Automated Release Build

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  # push:
  #   branches:
  #     - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # Fetch the official vcpkg repo directly
      - name: Checkout vcpkg
        uses: actions/checkout@v4
        with:
          repository: "https://github.com/Microsoft/vcpkg"
          path: "vcpkg"

      - name: Bootstrap vcpkg
        run: |
          ./vcpkg/bootstrap-vcpkg.sh
        shell: bash

      # Set up GitHub Actions Cache for vcpkg binary caching
      - name: Setup vcpkg Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/vcpkg
            ~/.vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      # Configure CMake passing the vcpkg toolchain file
      - name: Configure CMake with New Version
        run: |
          cmake -B build -S . \
            -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" \
            -DCMAKE_BUILD_TYPE=Release

      # Build the C++ Binary
      - name: Build C++ Binary
        run: cmake --build build --config Release
